services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: magic_recipe
      POSTGRES_PASSWORD: "0kyBOEI0vKOBjA6TdyrYbU_OWke0EjX-"
    volumes:
      - magic_recipe_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "3SCiuSkBEY-U21mp0kh6auUYpjZW-iqy"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: magic_recipe_test
      POSTGRES_PASSWORD: "QPQJ4j0JSmtZh37ZccVSi3HodS2QMsIw"
    volumes:
      - magic_recipe_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "T5Uy5QpxsE7p9Ch9Jf_0ZY5IDE8242_E"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  magic_recipe_data:
  magic_recipe_test_data:
